site:
  title: DBO
  start_page: dbo-architecture::index.adoc
content:
  sources:
    - url: .
      start_paths:
        - documentation
      branches:
        - "HEAD"
ui:
  bundle:
    url: antora-ui/ui-bundle.zip
    snapshot: true
  supplemental_files: ./antora-ui/supplemental-files
asciidoc:
  sourcemap: true
  extensions:
    - "asciidoctor-kroki"
  attributes:
    page-pagination: ''
