package cloud.jengu.dbo.conformance;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Renders a conformance run as the page a reader wants: the level first, the
 * detail underneath.
 *
 * <p>Written into the source tree rather than only into {@code build/}. A
 * report that lives in the build directory is a report nobody reads; one that
 * is committed shows up in a diff the moment the server's conformance moves,
 * which is the whole point of generating it.
 */
final class ConformanceReport {

    private ConformanceReport() {
    }

    static void write(Path directory, String fhirVersion, Conformance conformance) throws IOException {
        Files.createDirectories(directory);
        List<Conformance.Result> results = conformance.results();
        long supported = conformance.count(Conformance.Level.SUPPORTED);
        long failed = conformance.count(Conformance.Level.FAILED);
        long outOfScope = conformance.count(Conformance.Level.OUT_OF_SCOPE);
        long inScope = supported + failed;

        StringBuilder out = new StringBuilder();
        out.append("# FHIR ").append(fhirVersion).append(" conformance\n\n");
        out.append("<!-- Generated by :core:conformance:test. Do not edit by hand. -->\n\n");
        out.append("What this server does about the RESTful rules in the FHIR ")
                .append(fhirVersion).append(" specification, observed by driving\n")
                .append("the real HTTP surface against a real database.\n\n");

        out.append("**").append(supported).append(" of ").append(inScope)
                .append(" applicable rules supported");
        if (failed > 0) {
            out.append("; ").append(failed).append(" failing");
        }
        out.append(". ").append(outOfScope).append(" deliberately out of scope.**\n\n");

        out.append("A rule marked out of scope is one dbo has drawn a boundary around rather\n")
                .append("than one it gets wrong; the CapabilityStatement declares the same boundary.\n")
                .append("Search is tier 1 by design — see the REQ catalogue for what that covers.\n\n");

        Map<Conformance.Area, List<Conformance.Result>> byArea = new LinkedHashMap<>();
        for (Conformance.Area area : Conformance.Area.values()) {
            List<Conformance.Result> inArea = results.stream().filter(r -> r.area() == area).toList();
            if (!inArea.isEmpty()) {
                byArea.put(area, inArea);
            }
        }
        for (Map.Entry<Conformance.Area, List<Conformance.Result>> entry : byArea.entrySet()) {
            out.append("## ").append(entry.getKey().title).append("\n\n");
            out.append("| Rule | Specification | Level | Observed |\n");
            out.append("|---|---|---|---|\n");
            for (Conformance.Result r : entry.getValue()) {
                out.append("| ").append(escape(r.rule()))
                        .append(" | ").append(escape(r.reference()))
                        .append(" | ").append(r.level().label)
                        .append(" | ").append(escape(r.observed()))
                        .append(" |\n");
            }
            out.append('\n');
        }

        out.append("## What this report is not\n\n")
                .append("It is a statement of level, not a certificate. It exercises the RESTful\n")
                .append("interaction rules and the shapes of what comes back; it does not run an\n")
                .append("external conformance service, and it does not validate every response\n")
                .append("against the full StructureDefinition set. Where a response is round-tripped\n")
                .append("through the server's own write-validation gate, the report says so.\n");

        Files.writeString(directory.resolve("r" + fhirVersion.toLowerCase().replace("r", "") + ".md"),
                out.toString(), StandardCharsets.UTF_8);
    }

    private static String escape(String s) {
        return s == null ? "" : s.replace("|", "\\|").replace("\n", " ");
    }
}
