= Overview
:source-highlighter: highlight.js
:sectnums:

== Introduction

DB Objects is a lower level middleware component for overcoming different technical challenges related to storing data in database and exchanging data between software systems in microservice oriented solutions.
The main goals are:

. to allow true database separation in microservices.
This involves sharing of data between different microservices in standardized way
. defining and applying standardized enterprise level lifecycle for different type of data objects (including archiving, bringing info temporarily back from archive, deleting of data, auditing, changelog, tracing of chains of changes).

== Features

=== Cluster friendly: Multiple instances may access the storage in the same time

* [*] May run as vanilla java
* [*] May run as micronaut lib (auto inject)
* [*] May run in kube (multiple instances) (using vanilla or micronaut lib)
* [*] Auto-setup: The system initializes (and upgrades) it's database structure automatically (cluster friendly)

=== Searchable Object Storage

* [*] CRUD operations by object id
* [*] Object has type (for relations) and version (for payload versioning).
* [*] Each type of objects can be stored in the same (or separate) domains (database tables) for optimizing performance.
* [*] criteria based search (extraction of "envelope" from payload before each object save).

=== Identifiers: Stored objects can be identified by multiple identifiers

* [*] identifiers will be rebuilt before each save
* [*] rebuilt identifiers are used for recognizing the objects if id is not specified

=== References:

* [*] read object by including referenced objects
* [ ] Stored objects may "subscribe" to changes made in referenced objects (U by type or CUD id or by Type)

....
* reference can be one level (deeper references must be included exceptionally)
* is object type necessary??? yes, then we can create fhir references without additional queries.
* references are created using combinations of ObjectId+referenceType where
  - objectId is identifier of the referenced object
  - referenceType is object specific reference type;
* references are kept in separate table <prefix>_reference
* each object type has references which are controlled only by that object. this is achieved by owner_id column.
* multiple rows with the same owner_id & reference_type means one to many reference.
* each data storage may declare types of objects wanted to be listened.
  the signature of subscription would be:
  - objectType: string    - interested object type
  - referenceType: string - reference type
  - cardinality: enum(ONE, MANY)
    ONE - storage receives CRUD events related to changes in object with referred id (& referenceType)
    MANY - storage receives CRUD events to changes of all objects with referred objectType
* table <domain_prefix>_reference
  - owner_id       : string   // owner object id
  - referred_obj_id: string   // referred object id
  - reference_type : string   // reference type code. managed by owner object class
....

=== Archiving: Built in data archiving/deletion features for optimizing operational database.

* [ ] TBD
* [ ] Temporary restoration of data from the archive

=== Audit & Traceability: All (chained) data manipulations are traceable

* [ ] ELK stack + tempo + some tracing solution

=== Tooling: Audit & Traceability: Overview of "transaction logs", trace of all (chained) data manipulations & timing

* [ ] ELK stack + tempo + some tracing solution?
* [ ] Trace based monitoring/testing (Roland)?

=== Tooling: performance tracking based suggestions (& toolset) for solving potential performance issues

* [ ] splitting/merging object types between domains
* [ ] suggestions for configuring archiving
* [ ] "vacuum" - archiving/removing events

=== Tooling: web based database overview

* [ ] queries to objects in different domains, overview of metadata
* [ ] links to known scenarios (traces which affect current datatype)

== Concept

=== Node

An instance of the db objects system identified by node-id.
Node can share its state with another nodes (through shared database).
Node has 2 main goals:

- in shared (clustered) environments the node is responsible in coordinating and sharing information between clustered nodes (including coordinating of execution of administrative activities).
- the node manages the state of storages

=== Domain

- Represents the non shared discrete "database" for the one microservice.
- from technical perspective it's an automatically upgradeable (versioning) set of domain-specific db tables and functions for providing highly performing near realtime CRUD database for different types of objects.
- Domain also provides so-called storage "streaming" functionality which means near realtime publishing of changes of one specific storage to another domain (which may be even in different node cluster) in declarative way ( declared in Storage)

=== Storage

- a storage for concrete type (class) of objects which can be serialized to json string.
- Storage is always bound to one Domain where it is stored.
- storage provides tools for:
* defining fields for filtering and/or ordering of records,
* assigning additional identifiers to the objects (and making automatically updates in related objects),
* preparing sentences for full text search,
* hooks for additional custom processing e.g. creating additional data structures, running some business logic, publishing changes to other microservices

=== Database

Database is an abstraction for communicating with some real database in more meaningful way than JDBC for defining all needed db functionality.
At the moment postgres12+ specific optimized implementation is provided.

== Provided Functionality

=== Ability to upgrade the database structure

DB Objects is designed to be upgradeable without need to upgrade the database structure ... in most cases.
As objects are stored in database as json objects, the upgrade of the data structure is basically upgrading the version of the objects which will be done automatically by the converter provided by corresponding Storage.

Domain designs the storages for the specific microservice.
It also provides automatic update for the whole domain.
In real world it means cluster friendly ability upgrade the database structure for the Domain.
Current version of the domain db structure is kept in node level configuration it is shared between clustered nodes.
Domain versioning is implemented by following rules:

- all domain-related db stored procedures, tables and other database objects have prefix <domain-name>_<domain_version>_
- domain version is a positive integer
- for interacting the domain, the Node must support exactly the same version of the domain in database.
This is a pre conditional check for every call to the database.
- during node startup the node checks the domain version in database and if it supports the bigger version of domain it runs the domain upgrading scripts one by one until it reaches the maximum version it supports.
- Upgrading the domain version in database is an administrative task which blocks all other tasks during its execution.
- Only one administrative task is allowed to be run at time for one domain.
A suitable Node will block the domain for that.

==== Sharing domain state between nodes

Domain is designed to be cluster friendly.
Some activities can not be run in parallel Those activities are called administrative tasks.
Administrative tasks must be processed in a queue (not in parallel).
Some administrative tasks require to block even regular activities related to domain.

Properties used for coordinating running of administrative tasks (updated by the administrative task runner):

[source,json]
----
{ "domain-version": 1,            // current domain version
  "admin-task-in-progress": true, // if an administrative task is running at the moment or not.
  "admin-task": {                 // exists when "admin-task-in-progress": true
    "id": "<id>",                 // unique id (used in logs and acks from another nodes)
    "started-at": "timestamp",    // when the administrative task is started (db time)
    "heart-beat": "timestamp",    // must not be older than 5 seconds
                                  //   (otherwise other node may terminate the process)
    "domain-blocked": false,      // whether regular (parallellly running) domain actions are blocked or not
    "waiting-for-nodes": [        // waiting ack from listed nodes
      "nodeid"                    //   acks are expected to be written to the special table
    ]
  },
  "started-nodes" [               // list of active nodes bound to the Domain
    { "node-id": "<id>",          // node id
      "started-at": "timestamp",  // db timestamp when the node started
      "domain-version": 1,        // domain version supported by node
      "active": true,             // whether domain is active or passive (e.g. supports current domain version)
      "heart-beat": "timestamp"   // last event from the node
    }
  ],
  "latest-node-event": 1,         // latest processed node event
  "latest-data-event": 1          // latest processed data event
}
----

Administrative task may be processed by any Node.
The sequence of operations for the potential admin task:

1. administrative task may start when
- "admin-task-in-progress": false
- or "admin-task"."heart-beat" is older than 5sec (process timeout)
2. set "admin-task-in-progress": true and fill necessary "admin-task" fields
3. if previous admin process timeout detected ("admin-task"."heart-beat" is older than 5sec) audit log for that.
4. process node events:
- update list of started nodes (shut down nodes which are timed out)
- update "latest-node-event"
5. if it's a domain blocked event then
- set "admin-task"."domain-blocked"= true
- put all "started-nodes"."node-id" to "admin-task"."waiting-for-nodes" where "started-nodes"."active"=true
- wait for node/adminTaskId status ACK messages from all "waiting-for-nodes" (remove them)
6. process the administrative task
7. process the data events
- update "latest-data-event"
8. remove "admin-task" node
9. set "admin-task-in-progress": false

[plantuml,target=start-node,format=png]
....
participant Node as node
participant MasterNode as masterNode
queue       "db-objects-node-sync" as nodeSyncQueue
database "domain-state" as domainStateStorage
database "domain" as domainStorage

group "Node startup"
    activate node

    alt domainStateStorage is not set up
        node -> domainStateStorage: run domainStateStorageSetup scripts if necessary
    end

    loop for each registered domain
        node -> domainStateStorage: run createDomainStateIfNecessary (&become supernode)
activate domainStateStorage
            note left of domainStateStorage #aqua
              in transaction try insert (as supernode) and select
                - domainState json
                - ackNeeded (if insert or supernode timeout)
                - newDomain
                - masterNodeId
                - masterNodeHeartBeat
            end note
            node <-- domainStateStorage: domainState
deactivate domainStateStorage
        alt if newDomain
            node -> domainStorage: run createOrUpgradeDomainScriptsIfNecessary
        end

        node -> nodeSyncQueue: NODE_JOINED (node > domain)
activate nodeSyncQueue
            masterNode <-- nodeSyncQueue: NODE_JOINED
activate masterNode #DarkSalmon
                masterNode -> domainStateStorage: updateDomainState (newNode))
                masterNode -> nodeSyncQueue: ACK (NODE_JOINED)
deactivate masterNode
            node <-- nodeSyncQueue: ACK(NODE_JOINED)
deactivate nodeSyncQueue
    end

    loop for each registered domain ()
        alt domain node version is higher than storedNodeVersion
            node -> nodeSyncQueue: BECOME_MASTER
activate nodeSyncQueue
                masterNode <-- nodeSyncQueue: ACK(BECOME_MASTER)
activate masterNode #DarkSalmon
                    masterNode -> domainStateStorage: updateDomainState (newMasterNode))
                    masterNode -> nodeSyncQueue: DOMAIN_STATE(domainState with new masterNode)
                    masterNode --> node: switch to regular node
                    node <-- nodeSyncQueue: DOMAIN_STATE(domainState with new masterNode)
                    node -> nodeSyncQueue: ACK(DOMAIN_STATE)
                    masterNode <-- nodeSyncQueue: ACK(DOMAIN_STATE) // wait for ACKs from active nodes
deactivate masterNode

                alt for node which just became masterNode
                    node --> masterNode: switch to masterNode
activate masterNode #DarkSalmon
                        masterNode -> domainStorage: run createOrUpgradeDomainScriptsIfNecessary
                        masterNode -> domainStateStorage: updateDomainState (newDomainVersion))
                        masterNode -> nodeSyncQueue: DOMAIN_STATE(domainState with new masterNode)
                        node <-- nodeSyncQueue: DOMAIN_STATE(domainState with new masterNode)
                        node -> nodeSyncQueue: ACK(DOMAIN_STATE)
                        masterNode <-- nodeSyncQueue: ACK(DOMAIN_STATE) // wait for ACKs from active nodes
deactivate masterNode
deactivate nodeSyncQueue
                end
        end
    end
end
....

==== Starting a node

During node startup the following operations must be processed

1. if node state is missing then start a "domain-initialization" (blocking) administrative task.
2. if domain version is newer than start a "domain-upgrade" (blocking) administrative task.
3. add "node-started" node event.

==== Starting a node

During node shutdown the following operations must be processed

1. add "node-stopped" node event.
2. run a "event-processing" administrative task.

https://vertx.io/docs/4.2.7/vertx-pg-client/java/#_usage
