= References
:source-highlighter: highlight.js
:highlightjs-languages: protobuf
:sectnums:

== Concept

. Object info appears as `/dbo/app/domain/objectType` CRUD event
. App represents of scalable part of information (application is shared between nodes)
. only one node can be a master node at the same time
. everybody can create an event.
. events are processed by domains within master node.
. after successfully (?) processing an event, corresponding postChange event will be created in /dbo/app/domain/objectType

== This ma be outdated:


+
[source,protobuf]
....
message PersonExample {
  optional string name = 1;
  optional int32 id = 2;
  optional string email = 3;
}
....

       Book<creator> -> Person
         - bookStorage defines Person.class "creator" reference // init subscription
         - bookStorage implements createReferencedObjectsIfNecessary(Person.class, "creator", StorageObjCtx<book>, Collection<StorageObjCtx<person>>): Collection<StorageObjCtx<person>>
           - if references does not contain matching Book/<bookId>/"creator"/Person/<personId> reference, person ctx is not specified, otherwise assigned persons
           - if result does not contain person with referenced id then the reference will be removed
           - all existing results with if result contains person with referenced id then the reference will be created(and referenced object will be called to be updated)
           - BookStorage calls creation of new Person (by specified new random id)
           - BookStorage creates new reference Book/<bookId>/"creator"/Person/<personId> if necessary
           - If the creator is removed from the book then only the reference will be removed - not the person.
         - if the person referenced as creator is created/updated/deleted then:
           - in every storage where Person/<id> is referenced, the objectUpdated(Person, refType("creator"), StorageObjCtx<person>, Optional<storageObjCtx<book>>): Optional<storageObjCtx<book>> is called
             - if new person is created then storageObj<book> is empty (this can be used for collecting all references)
             - if result empty then nothing updated
             - if result nonEmpty then storageObject is updated