= Working in cluster
:source-highlighter: highlight.js
:sectnums:

== Main Concepts

- Application comes with a name.
Application defines a set of Domain names which belongs to the application.
Application data structure is labelled with version number which is provided by each node bound to the application.
The node with the highest application version will be propagated to masterNode.
- Domain represents the logical part of application (microservice).
Domain should be isolated and controlled by the one and only one application.
However, an application may control more domains - it depends on architectural decisions (amount of stored data, performance, access speed. etc).
- Node represents the physical part of application.
It's an instance of the application.
Node may be subscribed to zero or more domains.
Node uses specific version of db-objects.
The "current" version of db-objects is stored next to application.
The node may become to masterNode only if the version of the db-objects used by the node is equal or higher than the stored "current" version of db-objects.
The same story is with the application version.

== Use Cases

- [x] First activated app node becomes masterNode if the application is not registered yet.
- [ ] First activated app node becomes masterNode if the application is registered but there is no up-to-date.
existing masterNode and appVer is suitable and dboVer is suitable.
- [ ] First activated app node won't become masterNode if the application is registered but there is up up-to-date existing masterNode or appVer is not suitable or dboVer is not suitable.
- [ ] Second activated app node becomes masterNode if the application is registered but the node's appVer is newer than the stored appVer or the node's dboVer is newer than stored dboVer.
- [ ] Second activated app node won't become masterNode if the application is registered but there is up up-to-date existing masterNode or appVer is not suitable or dboVer is not suitable.
- [ ] Second running initially slave node becomes automatically masterNode when current masterNode timed out

== Communication

====
[plantuml,target=erd,format=png]
....
@startuml
entity dbo_app_state {
  * app_code : string <<unique>>
  * app_ver : number
  * dbo_ver : number
  * master_node : string
  * blocked : boolean
  * state_change_id : string
  * attributes : jsonb -- domain_names
}

entity dbo_node_state {
  * app_code : string
  * node_id : string
  * node_app_ver : number
  * mode_dbo_ver : number
  * node_heartbeat : number
  * status_code : string
  * is_master : boolean
  * known_app_state : string
}

node_state }|..|| app_state


@enduml


....

- Master node sends events to the slave nodes
- Slave node sends events to the master node
- When the node is starting, it must follow the "startup sequence":
1. reads the application state from db.
If the sppState does not exist, the state will be created by the node and the node starts the "becoming to masterNode" sequence.
If the appState exists with reference to the current masterNode - the node sends "SUBSCRIBED_TO_APP" event to the masterNode;
2. if the masterNode exists and the node has newer appVer or dboVer then the node switches itself to the passive mode for receiving ACK_APP_STATUS_UPDATED (with its ref as a superNode) or scanning of the presence of superNode.
- every node must update its presence in database regularly.
If the app-node record does not exist, it must start initialize startup sequence.
- becoming to master node must follow the sequence:
1. masterNode (or first suitable node when current masterNode is outdated or not set yet.) becomes aware of the new masterNode candidate.
In the next steps the "first suitable node" is considered as current masterNode
2. masterNode updates the application data by setting new candidate as a masterNode
3. masterNode sends the APP_STATUS_UPDATED event to the slave nodes.
4. master node waits ACK_APP_STATUS_UPDATED from each slave node or detects the nodes in non-responding state (by eliminating them from the db registry).
5. masterNode switches itself to the slave node mode
- when masterNode receives SUBSCRIBED_TO_APP event it checks if the new node has newer appVersion or dboVer.
Then it may activate the "becoming to masterNode" sequence.
- every slave node must check the presence of masterNode regularly.
If the masterNode is not present then the suitable node starts the "becoming to masterNode" sequence.
- if the node becomes to masterNode and its appVer is higher than dbAppVer then it:
1. updates the dbAppVer
2. sends the APP_STATUS_UPDATED event to the slave nodes.
3. continues a masterNode
- if the node becomes to masterNode and its dboVer is higher than dbDboVer then it:
1. updates the dbDboVer & sets the appBlocked=true.
2. sends the APP_STATUS_UPDATED event to the slave nodes.
3. waits ACK_APP_STATUS_UPDATED from each slave node or detects the nodes in non-responding state (by eliminating them from the db registry).
4. runs the dbo upgrade scripts
5. sets the appBlocked=false.
6. sends the APP_STATUS_UPDATED event to the slave nodes.
- if the slave node receives ACK_APP_STATUS_UPDATED event it:
1. reads the new app state from db
2. if appBlocked=true or dbAppVer>appVer or dbDboVer>dboVer then passivates the node otherwise activates the node.
3. if it became the supernode it starts the "becoming to masterNode" sequence otherwise sends the ACK_APP_STATUS_UPDATED to the superNode

== Db access Any node may

- create and update the app-node record (appName, nodeId, nodeState, presenceTimestamp)
- read the appState
- search for operational masterNode app-node record
- send the SUBSCRIBED_TO_APP event
- send the ACK_APP_STATUS_UPDATED event

Master node may

- update the appState
- remove the not responsive app-node record (TODO: need to verify that node cannot do harmful things by not having this record - bindig nodeid -> appName -> other tables data for hiding it)
- send APP_STATUS_UPDATED event

====

[plantuml,target=start-node,format=png]
....
participant Node as node
participant MasterNode as masterNode
queue       "db-objects-node-sync" as nodeSyncQueue
database "domain-state" as domainStateStorage
database "domain" as domainStorage

group "Node startup"
    activate node

    alt domainStateStorage is not set up
        node -> domainStateStorage: run domainStateStorageSetup scripts if necessary
    end

    loop for each registered domain
        node -> domainStateStorage: run createDomainStateIfNecessary (&become supernode)
activate domainStateStorage
            note left of domainStateStorage #aqua
              in transaction try insert (as supernode) and select
                - domainState json
                - ackNeeded (if insert or supernode timeout)
                - newDomain
                - masterNodeId
                - masterNodeHeartBeat
            end note
            node <-- domainStateStorage: domainState
deactivate domainStateStorage
        alt if newDomain
            node -> domainStorage: run createOrUpgradeDomainScriptsIfNecessary
        end

        node -> nodeSyncQueue: NODE_JOINED (node > domain)
activate nodeSyncQueue
            masterNode <-- nodeSyncQueue: NODE_JOINED
activate masterNode #DarkSalmon
                masterNode -> domainStateStorage: updateDomainState (newNode))
                masterNode -> nodeSyncQueue: ACK (NODE_JOINED)
deactivate masterNode
            node <-- nodeSyncQueue: ACK(NODE_JOINED)
deactivate nodeSyncQueue
    end

    loop for each registered domain ()
        alt domain node version is higher than storedNodeVersion
            node -> nodeSyncQueue: BECOME_MASTER
activate nodeSyncQueue
                masterNode <-- nodeSyncQueue: ACK(BECOME_MASTER)
activate masterNode #DarkSalmon
                    masterNode -> domainStateStorage: updateDomainState (newMasterNode))
                    masterNode -> nodeSyncQueue: DOMAIN_STATE(domainState with new masterNode)
                    masterNode --> node: switch to regular node
                    node <-- nodeSyncQueue: DOMAIN_STATE(domainState with new masterNode)
                    node -> nodeSyncQueue: ACK(DOMAIN_STATE)
                    masterNode <-- nodeSyncQueue: ACK(DOMAIN_STATE) // wait for ACKs from active nodes
deactivate masterNode

                alt for node which just became masterNode
                    node --> masterNode: switch to masterNode
activate masterNode #DarkSalmon
                        masterNode -> domainStorage: run createOrUpgradeDomainScriptsIfNecessary
                        masterNode -> domainStateStorage: updateDomainState (newDomainVersion))
                        masterNode -> nodeSyncQueue: DOMAIN_STATE(domainState with new masterNode)
                        node <-- nodeSyncQueue: DOMAIN_STATE(domainState with new masterNode)
                        node -> nodeSyncQueue: ACK(DOMAIN_STATE)
                        masterNode <-- nodeSyncQueue: ACK(DOMAIN_STATE) // wait for ACKs from active nodes
deactivate masterNode
deactivate nodeSyncQueue
                end
        end
    end
end
....


