package cloud.jengu.dbo.harness;

import cloud.jengu.dbo.promise.Promise;
import cloud.jengu.dbo.promise.PromiseStatus;
import cloud.jengu.dbo.promise.Proofs;
import cloud.jengu.dbo.promise.Registry;
import cloud.jengu.dbo.promise.Story;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * Where each story's legs are proven, and how far each story is from proving
 * itself.
 *
 * <p>A story declares the promises its journey rests on, and the catalogue
 * already says whether each is proven. It does not say <b>where</b>, so a
 * story can read as fully proven while every proof sits in a class that
 * builds a world of its own — which is the condition the ladder exists to
 * drain, invisible from the story that would notice it.
 *
 * <p>This says where. A leg is proven at the guide's own world, at a shared
 * tenant in the harness, or in a runtime some class built for itself; the
 * last is read from the worlds ledger rather than guessed, so the two
 * records cannot disagree.
 *
 * <p>A report rather than a ledger. It moves whenever a test moves, which is
 * the point of reading it and would be noise to ratchet.
 */
final class StoryCoverage {

    /** Where a proof runs, ordered by what it costs to run it. */
    private enum Where {
        GUIDE("the guide's world"),
        SHARED("a shared tenant"),
        OWN_WORLD("a world of its own"),
        ELSEWHERE("somewhere else"),
        NOWHERE("nowhere");

        private final String said;

        Where(String said) {
            this.said = said;
        }
    }

    private StoryCoverage() {
    }

    public static void main(String[] args) throws Exception {
        Path out = Path.of(args[0]);
        Set<String> ownWorlds = WorldsLedger.existing(Path.of(args[1])).keySet();
        ClassLoader loader = StoryCoverage.class.getClassLoader();
        Proofs proofs = Proofs.load(loader);
        Registry.Model model = Registry.load(loader).model(proofs);

        StringBuilder text = new StringBuilder("""
                # Where each story's legs are proven

                A story declares the promises its journey rests on. This says where each
                is proven, so a story that proves itself can be told from one whose legs
                are scattered. Generated by `./gradlew :core:harness:storyCoverage`.

                """);
        for (Story story : PromiseProjection.stories(model)) {
            Map<Where, Integer> tally = new LinkedHashMap<>();
            StringBuilder legs = new StringBuilder();
            for (Promise promise : story.promises()) {
                Set<String> sites = proofs.citing(promise);
                // A leg counts once, at the cheapest world it is proven in.
                // Counting sites instead says a leg proven three times is
                // three legs, and a story would read as owing more than it has.
                Where cheapest = Where.NOWHERE;
                Set<String> said = new TreeSet<>();
                for (String site : sites) {
                    Where where = whereOf(site, ownWorlds);
                    said.add(where.said);
                    if (where.ordinal() < cheapest.ordinal()) {
                        cheapest = where;
                    }
                }
                tally.merge(cheapest, 1, Integer::sum);
                if (cheapest != Where.GUIDE) {
                    legs.append("| `").append(model.codeOf(promise)).append("` | ")
                            .append(model.statusOf(promise)).append(" | ")
                            .append(said.isEmpty() ? Where.NOWHERE.said : String.join(", ", said))
                            .append(" |\n");
                }
            }
            text.append("## ").append(story.code()).append("\n\n")
                    .append(story.promises().size()).append(" legs: ")
                    .append(tally.getOrDefault(Where.GUIDE, 0)).append(" proven at the guide's ")
                    .append("world, ").append(tally.getOrDefault(Where.SHARED, 0))
                    .append(" at a shared tenant, ").append(tally.getOrDefault(Where.OWN_WORLD, 0))
                    .append(" only in a world built for one class, ")
                    .append(tally.getOrDefault(Where.NOWHERE, 0)).append(" nowhere.\n\n");
            if (legs.length() > 0) {
                text.append("| Leg | Status | Proven at |\n|---|---|---|\n").append(legs)
                        .append("\n");
            } else {
                text.append("This story proves itself.\n\n");
            }
        }
        Files.createDirectories(out.getParent());
        Files.writeString(out, text.toString(), StandardCharsets.UTF_8);
        System.out.println("story coverage: " + out);
    }

    /**
     * Which world a citing site runs in.
     *
     * <p>The guide's suite is one world for every step in it. A harness class
     * is shared unless the worlds ledger records it as building a runtime,
     * which is the same answer the build already ratchets rather than a
     * second opinion about it.
     */
    private static Where whereOf(String site, Set<String> ownWorlds) {
        String type = site.contains("#") ? site.substring(0, site.indexOf('#')) : site;
        String simple = type.contains(".") ? type.substring(type.lastIndexOf('.') + 1) : type;
        String outer = simple.contains("$") ? simple.substring(0, simple.indexOf('$')) : simple;
        if (type.startsWith("cloud.jengu.dbo.guide.")) {
            return Where.GUIDE;
        }
        if (type.startsWith("cloud.jengu.dbo.harness.")) {
            return ownWorlds.contains(outer) ? Where.OWN_WORLD : Where.SHARED;
        }
        return Where.ELSEWHERE;
    }
}
